name: Atualizar dados Parlamento

on:
  schedule:
    - cron: "0 3 * * *"       # todos os dias às 03:00 UTC
  workflow_dispatch:         # permite disparar manualmente

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write        # para permitir git push

    steps:
      # 1) Clone o repositório
      - uses: actions/checkout@v4

      # 2) Build & run dentro do mesmo DevContainer do VS Code
      - name: Executar dentro do DevContainer
        uses: devcontainers/ci@v0.3
        with:
          # caminho padrão para devcontainer.json
          devcontainerPath: .devcontainer
          runCmd: |
            # instalar dependências conforme postCreateCommand local
            pip install --no-cache-dir -r requirements.txt
            # rodar o scraper
            python scripts/parlamento_scraper.py

      # 3) Commit & push se houver novas ou modificadas CSVs
      - name: Commit & push se houver alterações
        run: |
          git config user.name  "github-actions"
          git config user.email "github-actions@github.com"

          # stage dos CSVs (novos e modificados)
          git add data/*.csv

          # verifica se algo foi adicionado ao índice
          if git diff --cached --quiet; then
            echo "Nenhuma alteração detectada."
          else
            git commit -m "Atualização automática dos dados do Parlamento"
            git push
          fi
